In [ ]:
import numpy as np
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [ ]:
arr1[2]

3

In [ ]:
arr1[2]=5

In [ ]:
arr1

array([1, 2, 5])

In [10]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
print("the shape is 2 row and 3 columns:",arr2.shape)

the shape is 2 row and 3 columns: (2, 3)


In [11]:
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])


3
3
3
4


In [17]:
print("create an array of type string")
arr3=np.array(['India','Chaina','USA','Mexico'])
arr3

create an array of type string


array(['India', 'Chaina', 'USA', 'Mexico'], dtype='<U6')

In [16]:
arr3[1]

'Chaina'

In [22]:
print("Using the arrange() & line space functionto evenly space values in a spacified in ")
arr=np.arange(0,20,2)
print(arr)

Using the arrange() & line space functionto evenly space values in a spacified in 
[ 0  2  4  6  8 10 12 14 16 18]


In [25]:
arr=np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [27]:
print("Create an array random  values between 0&1 in given shape")
arr=np.random.rand(10)
print(arr)
print('')
print("arranged in 3 rows and 4 col")
arr=np.random.rand(3,4)
print(arr)

Create an array random  values between 0&1 in given shape
[0.83748512 0.97478296 0.87506559 0.91574559 0.08814897 0.35500938
 0.87814798 0.56356294 0.41334118 0.8384708 ]

arranged in 3 rows and 4 col
[[0.49750197 0.54233533 0.09489715 0.94339464]
 [0.6506735  0.43512853 0.78241278 0.52424543]
 [0.07501704 0.60107884 0.29552905 0.52310265]]


In [31]:
print('create an array of constant value in given shape')
print(np.full((4,6),10))

create an array of constant value in given shape
[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [35]:
print('Repeat each element of an array by specified no.of times using repeate() and tile() functions')
arr=[0,1,2]
print(np.repeat(arr,3))

Repeat each element of an array by specified no.of times using repeate() and tile() functions
[0 0 0 1 1 1 2 2 2]


In [36]:
arr=[0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [37]:
print("create an identity matrix using eye()& identify() function")
im=np.eye(3)
print(im)

create an identity matrix using eye()& identify() function
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
im=np.identity(3)
print(im)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
print('Create 5X5 2D array for random numbers between 0&1 ')
arr=np.random.rand(5,5)
print(arr)

Create 5X5 2D array for random numbers between 0&1 
[[0.53419427 0.46692391 0.56067818 0.21403606 0.54975274]
 [0.01261226 0.2913308  0.69815557 0.19353157 0.44486776]
 [0.66869592 0.22500482 0.74343719 0.87499385 0.15629418]
 [0.72000898 0.5133566  0.53538566 0.7532207  0.77986299]
 [0.1362199  0.94694394 0.45011836 0.09877687 0.66920024]]


In [42]:
 print('Sum an arry along the column')
 print(np.sum(arr,axis=0))

Sum an arry along the column
[2.07173132 2.44356006 2.98777496 2.13455906 2.59997791]


In [43]:
print('Sum an array along the row')
print(np.sum(arr,axis=1))

Sum an array along the row
[2.32558515 1.64049795 2.66842596 3.30183492 2.30125931]


In [44]:
print('calculate mean, median,standard deviation & varience')
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

calculate mean, median,standard deviation & varience
0.48950413202555604
0.5341942657319015
0.25638456658597125
0.06573304598347633


In [45]:
print(' sort an array along the row using sort() function')
arr=np.random.rand(5,5)
print(arr)

 sort an array along the row using sort() function
[[0.6301554  0.96681015 0.48022898 0.92365479 0.2565502 ]
 [0.4818651  0.42768636 0.06752759 0.60635543 0.67065181]
 [0.16885584 0.16476363 0.59348842 0.55349436 0.22594369]
 [0.34016933 0.60872727 0.68049854 0.12262405 0.5140803 ]
 [0.52526833 0.12174472 0.35531037 0.39322818 0.00188893]]


In [46]:
print(np.sort(arr,axis=1))

[[0.2565502  0.48022898 0.6301554  0.92365479 0.96681015]
 [0.06752759 0.42768636 0.4818651  0.60635543 0.67065181]
 [0.16476363 0.16885584 0.22594369 0.55349436 0.59348842]
 [0.12262405 0.34016933 0.5140803  0.60872727 0.68049854]
 [0.00188893 0.12174472 0.35531037 0.39322818 0.52526833]]


In [47]:
print("append element to an array using yhe append() function")
arr=np.array([4,5,6,7])


append element to an array using yhe append() function


In [48]:
arr1=np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [49]:
arr2=np.append(arr,[9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [50]:
print("delete multiple element in an array")
arr2=np.array([4,5,6,7,9,10,11])
print(arr2)
print('')
arr5=np.delete(arr2,[1,4])
print(arr5)

delete multiple element in an array
[ 4  5  6  7  9 10 11]

[ 4  6  7 10 11]


In [51]:
arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])
cat=np.concatenate((arr1,arr2),axis=0)

In [52]:
cat

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [53]:
cat=np.concatenate((arr1,arr2),axis=1)
cat

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])